### ISSUE TITLE
API URL problem

### ISSUE THREAD

**Issue by Melchior01** [halfpetal/CapesAPI-ClientImplementation#5]
I don't know if this is the right place to post this but
L23 com.capesapi.UserAPI `URL url = new URL(baseURL + uuid.toString() + "/hasCape" + capeId);`
is missing a '/' before capeID, resulting in url looking like this
`http://capesapi.com/api/v1/uuid/hasCapecapeId`

**Comment by MatthewSH** [comment]
Oh wow, thank you. Didn't even notice. Changing now!
