### ISSUE TITLE
Cape works when running in Eclipse but not with an Exported Jar

### ISSUE THREAD

**Issue by kingcraftingnl** [halfpetal/CapesAPI-ClientImplementation#6]
Cape works when running in Eclipse but not with an Exported Jar

**Comment by MatthewSH** [comment]
It's worked with every other client, as the clients on the [client page](http://capesapi.com/clients) all work. Hm, is there something strange you're doing? Are you sure you're exporting our classes? Is there anything weird being logged?

**Comment by kingcraftingnl** [comment]
http://pastebin.com/TM6HXb2B
The AbstractClientPlayer class

**Comment by MatthewSH** [comment]
I don't need the player class, I need to know...

1. What Minecraft version?
2. Is there an error being displayed?
3. Are you making sure you're exporting the class?
4. Have you modified the classes to log out data and debug?

**Comment by kingcraftingnl** [comment]
1: 1.11.2
2: No errors i just sysout when the player has no cape,
3 the class its exported correctly
4 same as 3

**Comment by MatthewSH** [comment]
Start logging out everything, change the main CapesAPI class to log out when methods are run. Also, make sure you have a cape active, if there's no cape active...it will not display.

**Comment by kingcraftingnl** [comment]
ok i fixed the Issue it was due the new MC Launcher i removed my 1.11.2 so it downloaded a new .json and used that and now its fixed.
